const ApiError = require("../utils/ApiError");

const hackathons = [
  {
    id: "smart-india-hackathon",
    name: "Smart India Hackathon",
    organizer: "Government of India",
    domain: "GovTech",
    mode: "Hybrid",
    status: "Upcoming",
    difficulty: "Intermediate",
    registration: "Free",
    deadline: "20 Jul 2026",
    registrationDeadline: "2026-07-02T10:12:00Z",
    eventDates: "10-12 Aug 2026",
    location: "India",
    prizePool: "National recognition and cash awards",
    logo: "SIH",
    officialWebsite: "https://www.sih.gov.in/",
    description:
      "India's flagship innovation challenge connecting students with government and industry problem statements.",
    prizeBand: "High",
  },
  {
    id: "google-solution-challenge",
    name: "Google Solution Challenge",
    organizer: "Google Developer Groups",
    domain: "AI",
    mode: "Online",
    status: "Upcoming",
    difficulty: "Intermediate",
    registration: "Free",
    deadline: "15 Feb 2026",
    registrationDeadline: "2026-02-15T23:59:00Z",
    eventDates: "20-22 Feb 2026",
    location: "Global",
    prizePool: "$50K+ prizes and mentorship",
    logo: "G",
    officialWebsite: "https://developers.google.com/community/gdsc-solution-challenge",
    description:
      "Student teams build solutions with Google technology for one of the UN Sustainable Development Goals.",
    prizeBand: "High",
  },
  {
    id: "microsoft-imagine-cup",
    name: "Microsoft Imagine Cup",
    organizer: "Microsoft",
    domain: "Cloud",
    mode: "Online",
    status: "Upcoming",
    difficulty: "Advanced",
    registration: "Free",
    deadline: "11 Mar 2026",
    registrationDeadline: "2026-03-11T23:59:00Z",
    eventDates: "18-20 Mar 2026",
    location: "Global",
    prizePool: "$100K+ and Azure credits",
    logo: "M",
    officialWebsite: "https://imaginecup.microsoft.com/",
    description:
      "Microsoft's long-running student startup and product challenge for ambitious technical teams.",
    prizeBand: "High",
  },
  {
    id: "ethindia",
    name: "ETHIndia",
    organizer: "Devfolio",
    domain: "Blockchain",
    mode: "Offline",
    status: "Upcoming",
    difficulty: "Advanced",
    registration: "Free",
    deadline: "28 Sep 2025",
    registrationDeadline: "2026-09-28T23:59:00Z",
    eventDates: "10-12 Oct 2025",
    location: "India",
    prizePool: "Crypto grants, bounties and prizes",
    logo: "ETH",
    officialWebsite: "https://ethindia.co/",
    description:
      "One of the largest Ethereum-focused hackathons for builders exploring web3, smart contracts and tooling.",
    prizeBand: "High",
  },
  {
    id: "hackcbs",
    name: "HackCBS",
    organizer: "Shaheed Sukhdev College of Business Studies",
    domain: "Web Development",
    mode: "Offline",
    status: "Ended",
    difficulty: "Intermediate",
    registration: "Free",
    deadline: "10 Jan 2026",
    registrationDeadline: "2026-01-10T23:59:00Z",
    eventDates: "17-19 Jan 2026",
    location: "Delhi, India",
    prizePool: "Cash prizes and swag",
    logo: "HC",
    officialWebsite: "https://hackcbs.tech/",
    description:
      "A student-led hackathon bringing together makers, designers and builders from across India.",
    prizeBand: "Medium",
  },
  {
    id: "hacknitr",
    name: "HackNITR",
    organizer: "NIT Rourkela",
    domain: "AI",
    mode: "Offline",
    status: "Upcoming",
    difficulty: "Intermediate",
    registration: "Free",
    deadline: "05 Aug 2026",
    registrationDeadline: "2026-08-05T23:59:00Z",
    eventDates: "25-27 Aug 2026",
    location: "Rourkela, India",
    prizePool: "Cash prizes and sponsorships",
    logo: "HN",
    officialWebsite: "https://hacknitr.com/",
    description: "A campus hackathon that blends engineering, design and product thinking.",
    prizeBand: "Medium",
  },
  {
    id: "hackthisfall",
    name: "HackThisFall",
    organizer: "HackThisFall Community",
    domain: "Open Source",
    mode: "Offline",
    status: "Upcoming",
    difficulty: "Intermediate",
    registration: "Free",
    deadline: "12 Apr 2026",
    registrationDeadline: "2026-04-12T23:59:00Z",
    eventDates: "02-04 May 2026",
    location: "India",
    prizePool: "Prizes, mentorship and community recognition",
    logo: "HF",
    officialWebsite: "https://hackthisfall.com/",
    description:
      "A community-first hackathon focused on inclusive building, open source and collaboration.",
    prizeBand: "Medium",
  },
  {
    id: "jpmorgan-code-for-good",
    name: "JPMorgan Code for Good",
    organizer: "JPMorgan Chase",
    domain: "Social Impact",
    mode: "Offline",
    status: "Upcoming",
    difficulty: "Intermediate",
    registration: "Free",
    deadline: "18 Jun 2026",
    registrationDeadline: "2026-06-18T23:59:00Z",
    eventDates: "08-09 Jul 2026",
    location: "Global",
    prizePool: "Internship consideration and mentorship",
    logo: "CF",
    officialWebsite: "https://careers.jpmorgan.com/us/en/students/programs/code-for-good",
    description:
      "A social-impact coding event where teams build solutions for nonprofit organizations.",
    prizeBand: "High",
  },
  {
    id: "nasa-space-apps",
    name: "NASA Space Apps Challenge",
    organizer: "NASA",
    domain: "Data Science",
    mode: "Hybrid",
    status: "Upcoming",
    difficulty: "Intermediate",
    registration: "Free",
    deadline: "30 Jul 2026",
    registrationDeadline: "2026-07-30T23:59:00Z",
    eventDates: "04-06 Oct 2026",
    location: "Global",
    prizePool: "Global recognition and NASA exposure",
    logo: "NASA",
    officialWebsite: "https://www.spaceappschallenge.org/",
    description:
      "NASA's global hackathon encouraging participants to solve challenges using open space and Earth data.",
    prizeBand: "High",
  },
  {
    id: "hackmit",
    name: "HackMIT",
    organizer: "MIT",
    domain: "AI",
    mode: "Offline",
    status: "Upcoming",
    difficulty: "Advanced",
    registration: "Free",
    deadline: "22 Aug 2026",
    registrationDeadline: "2026-08-22T23:59:00Z",
    eventDates: "12-14 Sep 2026",
    location: "Cambridge, USA",
    prizePool: "Sponsored prizes and mentorship",
    logo: "HM",
    officialWebsite: "https://hackmit.org/",
    description:
      "MIT's flagship student hackathon for high-intensity prototyping and technical ambition.",
    prizeBand: "High",
  },
  {
    id: "mlh-global-hack-week",
    name: "MLH Global Hack Week",
    organizer: "Major League Hacking",
    domain: "Web Development",
    mode: "Online",
    status: "Live",
    difficulty: "Beginner",
    registration: "Free",
    deadline: "Rolling weekly cohorts",
    registrationDeadline: null,
    eventDates: "Ongoing weekly sessions",
    location: "Global",
    prizePool: "Swag, prizes and learning tracks",
    logo: "MLH",
    officialWebsite: "https://events.mlh.io/",
    description: "A globally distributed series of hack-week events, workshops and mini challenges.",
    prizeBand: "Medium",
  },
  {
    id: "angelhack",
    name: "AngelHack Global Hackathon",
    organizer: "AngelHack",
    domain: "Mobile Development",
    mode: "Online",
    status: "Upcoming",
    difficulty: "Intermediate",
    registration: "Free",
    deadline: "Monthly registration cohorts",
    registrationDeadline: null,
    eventDates: "Rolling monthly events",
    location: "Global",
    prizePool: "Program prizes and startup visibility",
    logo: "AH",
    officialWebsite: "https://angelhack.com/",
    description:
      "AngelHack connects builders with sponsors, mentors and product challenges around the world.",
    prizeBand: "Medium",
  },
  {
    id: "hack2skill-events",
    name: "Hack2Skill Events",
    organizer: "Hack2Skill",
    domain: "Cloud",
    mode: "Hybrid",
    status: "Live",
    difficulty: "Intermediate",
    registration: "Free",
    deadline: "23 Jun 2026",
    registrationDeadline: "2026-06-23T23:59:00Z",
    eventDates: "24-26 Jun 2026",
    location: "India",
    prizePool: "Cash prizes and certificates",
    logo: "H2",
    officialWebsite: "https://hack2skill.com/",
    description:
      "Hack2Skill hosts challenge programs and hackathons with sponsor-backed problem statements.",
    prizeBand: "Medium",
  },
  {
    id: "hack-the-future-devfolio",
    name: "Hack the Future",
    organizer: "Devfolio",
    domain: "AI",
    mode: "Offline",
    status: "Upcoming",
    difficulty: "Advanced",
    registration: "Free",
    deadline: "14 Sep 2026",
    registrationDeadline: "2026-09-14T23:59:00Z",
    eventDates: "03-05 Oct 2026",
    location: "India",
    prizePool: "Sponsor prizes and grants",
    logo: "DTF",
    officialWebsite: "https://devfolio.co/hackathons",
    description:
      "Devfolio's hackathon discovery hub featuring community events and sponsored build challenges.",
    prizeBand: "High",
  },
  {
    id: "walmart-sparkathon",
    name: "Walmart Sparkathon",
    organizer: "Walmart Global Tech",
    domain: "Data Science",
    mode: "Hybrid",
    status: "Upcoming",
    difficulty: "Advanced",
    registration: "Paid",
    deadline: "01 Sep 2026",
    registrationDeadline: "2026-09-01T23:59:00Z",
    eventDates: "18-20 Sep 2026",
    location: "India",
    prizePool: "Cash prizes, mentorship and hiring visibility",
    logo: "WS",
    officialWebsite: "https://sparkathon.walmart.com/",
    description:
      "Walmart's innovation challenge for solving large-scale retail and tech problems.",
    prizeBand: "High",
  },
  {
    id: "flipkart-grid",
    name: "Flipkart GRiD",
    organizer: "Flipkart",
    domain: "Cloud",
    mode: "Online",
    status: "Upcoming",
    difficulty: "Advanced",
    registration: "Free",
    deadline: "05 Aug 2026",
    registrationDeadline: "2026-08-05T23:59:00Z",
    eventDates: "12-14 Aug 2026",
    location: "India",
    prizePool: "Cash prizes and placements",
    logo: "FG",
    officialWebsite: "https://www.flipkartgrid.com/",
    description:
      "Flipkart's engineering challenge for students focused on product and systems problems.",
    prizeBand: "High",
  },
  {
    id: "adobe-india-hackathon",
    name: "Adobe India Hackathon",
    organizer: "Adobe",
    domain: "AI",
    mode: "Online",
    status: "Upcoming",
    difficulty: "Advanced",
    registration: "Free",
    deadline: "16 Jul 2026",
    registrationDeadline: "2026-07-16T23:59:00Z",
    eventDates: "30 Jul-01 Aug 2026",
    location: "India",
    prizePool: "Cash prizes and internship visibility",
    logo: "AD",
    officialWebsite: "https://adobeindiahackathon.com/",
    description:
      "Adobe's competitive student hackathon centered on creative and technical problem solving.",
    prizeBand: "High",
  },
  {
    id: "unstop-challenges",
    name: "Unstop Challenges",
    organizer: "Unstop",
    domain: "Web Development",
    mode: "Online",
    status: "Live",
    difficulty: "Beginner",
    registration: "Free",
    deadline: "Ongoing",
    registrationDeadline: null,
    eventDates: "Always on",
    location: "India",
    prizePool: "Cash prizes, rewards and certificates",
    logo: "U",
    officialWebsite: "https://unstop.com/",
    description:
      "A large challenge platform hosting hackathons, competitions and student hiring events.",
    prizeBand: "Medium",
  },
  {
    id: "hack-with-india",
    name: "Hack With India",
    organizer: "Hack With India Community",
    domain: "Mobile Development",
    mode: "Online",
    status: "Upcoming",
    difficulty: "Beginner",
    registration: "Free",
    deadline: "07 Oct 2026",
    registrationDeadline: "2026-10-07T23:59:00Z",
    eventDates: "21-23 Oct 2026",
    location: "India",
    prizePool: "Community prizes and mentorship",
    logo: "HWI",
    officialWebsite: "https://hackwithindia.in/",
    description:
      "A builder-friendly hackathon with a strong student community and practical mentorship.",
    prizeBand: "Low",
  },
  {
    id: "techkriti-hackathon",
    name: "Techkriti Hackathon",
    organizer: "IIT Kanpur",
    domain: "Robotics",
    mode: "Offline",
    status: "Upcoming",
    difficulty: "Advanced",
    registration: "Free",
    deadline: "10 Mar 2026",
    registrationDeadline: "2026-03-10T23:59:00Z",
    eventDates: "20-22 Mar 2026",
    location: "Kanpur, India",
    prizePool: "Cash prizes and event sponsorships",
    logo: "TK",
    officialWebsite: "https://techkriti.org/",
    description:
      "A premier technical festival hackathon with strong engineering and robotics tracks.",
    prizeBand: "High",
  },
  {
    id: "hackathon-by-hackerearth",
    name: "HackerEarth Hackathons",
    organizer: "HackerEarth",
    domain: "AI",
    mode: "Online",
    status: "Live",
    difficulty: "Intermediate",
    registration: "Free",
    deadline: "Ongoing",
    registrationDeadline: null,
    eventDates: "Rolling challenge windows",
    location: "Global",
    prizePool: "Cash prizes and recruiting visibility",
    logo: "HE",
    officialWebsite: "https://www.hackerearth.com/challenges/",
    description:
      "Challenge listings and branded hackathons hosted by companies through HackerEarth.",
    prizeBand: "Medium",
  },
  {
    id: "devpost-hackathons",
    name: "Devpost Hackathons",
    organizer: "Devpost",
    domain: "Open Source",
    mode: "Online",
    status: "Live",
    difficulty: "Beginner",
    registration: "Free",
    deadline: "Ongoing",
    registrationDeadline: null,
    eventDates: "Always on",
    location: "Global",
    prizePool: "Sponsor-backed prizes",
    logo: "DP",
    officialWebsite: "https://devpost.com/hackathons",
    description:
      "A popular platform for discovering and joining sponsored hackathons and open calls.",
    prizeBand: "Medium",
  },
  {
    id: "hackerearth-open-challenges",
    name: "HackerEarth Open Challenges",
    organizer: "HackerEarth",
    domain: "Cyber Security",
    mode: "Online",
    status: "Upcoming",
    difficulty: "Intermediate",
    registration: "Free",
    deadline: "15 Nov 2026",
    registrationDeadline: "2026-11-15T23:59:00Z",
    eventDates: "26-28 Nov 2026",
    location: "Global",
    prizePool: "Cash prizes and certificates",
    logo: "HO",
    officialWebsite: "https://www.hackerearth.com/challenges/",
    description:
      "Open challenge listings for students and professionals across multiple domains.",
    prizeBand: "Low",
  },
  {
    id: "hackathon-radar-community",
    name: "HackRadar Community Challenge",
    organizer: "HackRadar",
    domain: "IoT",
    mode: "Hybrid",
    status: "Upcoming",
    difficulty: "Beginner",
    registration: "Free",
    deadline: "25 Aug 2026",
    registrationDeadline: "2026-08-25T23:59:00Z",
    eventDates: "05-07 Sep 2026",
    location: "Global",
    prizePool: "Community recognition",
    logo: "HR",
    officialWebsite: "https://hackradar.com/",
    description:
      "Placeholder community listing used for local product testing and future event expansion.",
    prizeBand: "Low",
  },
  {
    id: "opensource-sprint",
    name: "Open Source Sprint",
    organizer: "MLH and community partners",
    domain: "Open Source",
    mode: "Online",
    status: "Upcoming",
    difficulty: "Beginner",
    registration: "Free",
    deadline: "Rolling sprint windows",
    registrationDeadline: null,
    eventDates: "Ongoing seasonal cohorts",
    location: "Global",
    prizePool: "Swag and mentorship",
    logo: "OSS",
    officialWebsite: "https://events.mlh.io/",
    description:
      "A beginner-friendly open source sprint for contributors building public good projects.",
    prizeBand: "Low",
  },
];

function listHackathons() {
  return hackathons;
}

function getHackathonById(id) {
  const hackathon = hackathons.find((item) => item.id === id);
  if (!hackathon) {
    throw new ApiError(404, "Hackathon not found");
  }
  return hackathon;
}

module.exports = {
  listHackathons,
  getHackathonById,
};
